export const SYSTEM_RULES = {
  CURRENCY: "USDT",
  NETWORK: "BSC",
  TOKEN_STANDARD: "BEP20",

  MACHINE_DURATION_CYCLES: 20,
  MACHINE_CYCLE_HOURS: 24,
  PAYOUT_MULTIPLIER: 2,

  MIN_WITHDRAWAL_USDT: 1,
  WITHDRAWAL_COOLDOWN_HOURS: 24,

  POWER_PER_VALID_REFERRAL_PERCENT: 2.5,
  MAX_POWER_PERCENT: 30,
  VALID_REFERRALS_FOR_MAX_POWER: 12,

  EXTRA_REFERRALS_PER_REWARD_MACHINE: 10,

  FREE_MACHINE_VIRTUAL_PRINCIPAL_USDT: 1,
  REWARD_MACHINE_VIRTUAL_PRINCIPAL_USDT: 7,

  MIN_BSC_CONFIRMATIONS: 12,
  DEPOSIT_ORDER_EXPIRES_HOURS: 6
} as const;

export const MACHINE_PLAN_SLUGS = {
  PICO_INICIAL: "pico-inicial",
  EXCAVADORA: "excavadora",
  PERFORADORA: "perforadora",
  TRITURADORA: "trituradora",
  PLANTA_ELITE: "planta-elite",
  DRAGALINA: "dragalina",
  COLOSO: "coloso",
  AURORA: "aurora"
} as const;

export const PAID_MACHINE_PRICES_USDT = [7, 24, 50, 100, 500, 1000] as const;

export const MACHINE_TYPES = {
  FREE: "FREE",
  PAID: "PAID",
  REWARD: "REWARD"
} as const;
